version: '3.4'

services:
  authenticationservice:
    image: ${DOCKER_REGISTRY-}authenticationservice
    build:
      context: .
      dockerfile: AuthenticationService/Dockerfile
    networks:
        - rabbitmq_net

  profileservice:
    image: ${DOCKER_REGISTRY-}profileservice
    build:
      context: .
      dockerfile: ProfileService/Dockerfile
    networks:
        - rabbitmq_net

  recommendationservice:
    image: ${DOCKER_REGISTRY-}recommendationservice
    build:
      context: .
      dockerfile: RecommendationService/Dockerfile
    networks:
        - rabbitmq_net

  commentservice:
    image: ${DOCKER_REGISTRY-}commentservice
    build:
      context: .
      dockerfile: CommentService/Dockerfile
    networks:
        - rabbitmq_net

  rabbitmq:
    hostname: 'mabbit'
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge