version: '3.4'

services:
  authenticationservice:
    image: ${DOCKER_REGISTRY-}authenticationservice
    build:
      context: .
      dockerfile: AuthenticationService/Dockerfile
    networks:
        - rabbitmq_net

  profileservice:
    image: ${DOCKER_REGISTRY-}profileservice
    build:
      context: .
      dockerfile: ProfileService/Dockerfile
    networks:
        - rabbitmq_net

  recommendationservice:
    image: ${DOCKER_REGISTRY-}recommendationservice
    build:
      context: .
      dockerfile: RecommendationService/Dockerfile
    networks:
        - rabbitmq_net

  commentservice:
    image: ${DOCKER_REGISTRY-}commentservice
    build:
      context: .
      dockerfile: CommentService/Dockerfile
    networks:
        - rabbitmq_net

  rabbitmq:
    hostname: 'mabbit'
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    networks:
        - rabbitmq_net

  sqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest
    networks:
        - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge